# syntax=docker/dockerfile:1.18-labs
# -------- Production Builder --------
FROM node:24-alpine AS builder

RUN corepack enable pnpm && corepack install -g pnpm@10.14.0

WORKDIR /fortuna

# Copy manifests
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/
COPY --parents packages/*/package.json ./

# Install workspace deps
RUN pnpm install --frozen-lockfile

# Copy in only what the web app needs
COPY apps/web apps/web
COPY packages packages

# Build the app
RUN pnpm turbo build --filter=web



# -------- Production --------
FROM node:24-alpine AS prod

WORKDIR /fortuna

RUN apk add --no-cache curl

COPY --from=builder /fortuna/apps/web/.next/standalone ./
COPY --from=builder /fortuna/apps/web/public ./apps/web/public
COPY --from=builder /fortuna/apps/web/.next/static ./apps/web/.next/static

CMD ["node", "apps/web/server.js"]



# -------- Development (with hot reload) --------
FROM node:24-alpine AS dev

RUN apk add --no-cache curl

RUN corepack enable pnpm && corepack install -g pnpm@10.14.0

WORKDIR /fortuna

CMD ["pnpm", "turbo", "start:dev", "--filter=web"]
