packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  cpu-features: false
  esbuild: true
  nx: true
  protobufjs: false
  sharp: true
  ssh2: false
  unrs-resolver: true

catalog:
  '@biomejs/biome': 2.4.15
  '@types/jest': 30.0.0
  '@types/node': 24.12.4
  jest: 30.4.2
  typescript: 6.0.3

injectWorkspacePackages: true
