ARG NODE_TAG=24-bookworm

FROM node:${NODE_TAG}

ARG PLAYWRIGHT_VERSION=1.60.0
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npm i -g playwright@${PLAYWRIGHT_VERSION} \
 && playwright --version \
 && playwright install --with-deps chromium firefox webkit

RUN ls -la /ms-playwright
